[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma db push --skip-generate && cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public && node .next/standalone/server.js"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
